#Sebastian Firsaev 27/09/23
#Makefile



CC=g++
CFLAGS=-std=c++11 -pthread -Wall
MUTFILES=Semaphore.cpp Semaphore.h
DFLAGS=-O8 -g

SIMPLE: helloThreads.cpp
	g++ -std=c++11 -pthread helloThreads.cpp


CLEAN:
	rm *.o
